 CREATE TABLE `REPORT_game_detail` (
  `rpt_time` bigint(20) DEFAULT NULL COMMENT '最新行为时间',
  `rpt_ip` varchar(30) COLLATE utf8_bin DEFAULT NULL COMMENT '登陆IP',
  `rpt_uri` varchar(330) COLLATE utf8_bin DEFAULT NULL COMMENT '用户行为标识',
  `rpt_method` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '方法',
  `rpt_os` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '操作系统标识',
  `rpt_os_version` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '操作系统版本',
  `rpt_device` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '设备名称',
  `rpt_browser` varchar(128) COLLATE utf8_bin DEFAULT NULL COMMENT '浏览器名称',
  `rpt_browser_version` varchar(256) COLLATE utf8_bin DEFAULT NULL COMMENT '浏览器版本',
  `rpt_passport` varchar(256) COLLATE utf8_bin DEFAULT NULL COMMENT '认证',
  `rpt_sub_name` varchar(256) COLLATE utf8_bin DEFAULT NULL COMMENT '账号名称',
  `rpt_game_id` int(11) DEFAULT NULL COMMENT '游戏编码',
  `rpt_hash` varchar(256) COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT 'key hash',
  `rpt_created` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`rpt_hash`),
  KEY `IDX_REPORT_game_detail_rpt_time` (`rpt_time`),
  KEY `IDX_REPORT_game_detail_rpt_ip` (`rpt_ip`),
  KEY `IDX_REPORT_game_detail_rpt_uri` (`rpt_uri`),
  KEY `IDX_REPORT_game_detail_rpt_method` (`rpt_method`),
  KEY `IDX_REPORT_game_detail_rpt_os` (`rpt_os`),
  KEY `IDX_REPORT_game_detail_rpt_device` (`rpt_device`),
  KEY `IDX_REPORT_game_detail_rpt_browser` (`rpt_browser`),
  KEY `IDX_REPORT_game_detail_rpt_passport` (`rpt_passport`),
  KEY `IDX_REPORT_game_detail_rpt_sub_name` (`rpt_sub_name`),
  KEY `IDX_REPORT_game_detail_rpt_game_id` (`rpt_game_id`),
  KEY `idx_REPORT_game_detail_rpt_created` (`rpt_created`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='网页登陆行为统计信息'